name: Deploy  Application

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files for debugging
      run: ls -la
      shell: bash

    - name: Setup FTP deployment
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: https://nibiz.online/PizBangla
        username: pizbangla@nibiz.online
        password: i3+aXlL}?z+1
        local-dir: ./
        server-dir: /
        exclude: .gitignore


