name: Deploy Laravel Application

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files for debugging
      run: ls -la
      shell: bash

    - name: Setup FTP deployment
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.upseba.com.bd
        username: lms.upseba.com.bd@lms.upseba.com.bd
        password: Monaem66@@
        local-dir: ./
        server-dir: /
        exclude: .gitignore


